SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY DATEDIFF(DATE_FORMAT(ANIMAL_OUTS.DATETIME, '%Y-%m-%d'), DATE_FORMAT(ANIMAL_INS.DATETIME, '%Y-%m-%d')) DESC
LIMIT 2;