SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d'),
    CASE
    WHEN DATEDIFF(DATE_FORMAT(OUT_DATE, '%Y-%m-%d'), DATE_FORMAT('2022-05-01', '%Y-%m-%d')) <= 0
        THEN '출고완료'
    WHEN OUT_DATE IS NULL
        THEN '출고미정'
    ELSE '출고대기'
    END AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID